version: '3.1'

services:
  ioiprint:
    build: .
    ports:
    - 5000:5000  # The first 5000 is the port the print service will be on
    volumes:
    - ./uploads/:/usr/src/ioiprint/uploads/  # the directory before ":" is the uploads directory on the host machine
    environment:
      NETADMIN_URL: netadmin.ioi2017.org  # the address of IOI Net Administration System
      UPLOADS_DIRECTORY: /usr/src/ioiprint/uploads/
      CUPS_ADDRESS: cups-back:631
      # The printer or class names used for contest zones (They should exist in cups-back server)
      ZONE_A_PRINTER: floor1
      ZONE_B_PRINTER: floor1
      ZONE_C_PRINTER: floor1
      ZONE_D_PRINTER: floor1
      ZONE_E_PRINTER: floor2
      ZONE_F_PRINTER: floor2
      ZONE_G_PRINTER: floor2
      ZONE_H_PRINTER: floor2
      DEFAULT_PRINTER: default  # The printer or class name used for translation and mass requests

  cups-front:
    build: cups/
    ports:
    - 631:631
    environment:
      # Username and password used for cups-front server
      CUPS_USER_ADMIN: admin
      CUPS_USER_PASSWORD: 123456

  cups-back:
    image: aadl/cups-alpine:2.2.3
    ports:
    - 6631:631
    environment:
      # Username and password used for cups-back server
      CUPS_USER_ADMIN: admin
      CUPS_USER_PASSWORD: 123456
